Fix for "AttributeError: 'list' object has no attribute 'get'" in StaticResolver
On success call_api() returns a list of dicts which StaticResolver
doesn't seem to expect. On failure just the single dict is returned.